# Symbolic matrix computation in Python -- with Sympy

Sympy is included in the Anaconda distribution.

For more information about Sympy, see  <a href="http://sympy.org">sympy.org</a>

In [1]:
import numpy as np

In [2]:
from sympy import *

# This imports many useful functions, like sin(), cos(), etc.
# They can be used without having to give a module name.

In [3]:
phi, theta = symbols('phi theta')  #  declare phi and theta to be symbolic variables

In [4]:
Rotation = lambda t: np.matrix([[cos(t), -sin(t)], [sin(t), cos(t)]])

In [5]:
Rotation(theta)

matrix([[cos(theta), -sin(theta)],
        [sin(theta), cos(theta)]], dtype=object)

In [6]:
matrix_simplify = np.vectorize(simplify)

In [7]:
matrix_simplify( Rotation(theta) * Rotation(-theta) )

matrix([[1, 0],
        [0, 1]], dtype=object)

In [8]:
matrix_simplify( Rotation(theta) * Rotation(+theta) )

matrix([[cos(2*theta), -sin(2*theta)],
        [sin(2*theta), cos(2*theta)]], dtype=object)

In [9]:
Rotation(theta) * Rotation(phi)

matrix([[-sin(phi)*sin(theta) + cos(phi)*cos(theta),
         -sin(phi)*cos(theta) - sin(theta)*cos(phi)],
        [sin(phi)*cos(theta) + sin(theta)*cos(phi),
         -sin(phi)*sin(theta) + cos(phi)*cos(theta)]], dtype=object)

In [10]:
matrix_simplify( Rotation(theta) * Rotation(phi) )

matrix([[cos(phi + theta), -sin(phi + theta)],
        [sin(phi + theta), cos(phi + theta)]], dtype=object)

In [11]:
Reflection = lambda t: np.matrix([[cos(t), sin(t)], [sin(t), -cos(t)]])

In [12]:
Reflection(theta)

matrix([[cos(theta), sin(theta)],
        [sin(theta), -cos(theta)]], dtype=object)

In [13]:
matrix_simplify( Reflection(theta) * Reflection(theta) )

matrix([[1, 0],
        [0, 1]], dtype=object)

In [14]:
Reflection(theta) * Reflection(phi)

matrix([[sin(phi)*sin(theta) + cos(phi)*cos(theta),
         sin(phi)*cos(theta) - sin(theta)*cos(phi)],
        [-sin(phi)*cos(theta) + sin(theta)*cos(phi),
         sin(phi)*sin(theta) + cos(phi)*cos(theta)]], dtype=object)

In [15]:
Rotation(theta - phi)

matrix([[cos(phi - theta), sin(phi - theta)],
        [-sin(phi - theta), cos(phi - theta)]], dtype=object)

In [16]:
matrix_simplify( Reflection(theta) * Reflection(phi)  -  Rotation(theta - phi) )

matrix([[0, 0],
        [0, 0]], dtype=object)